
    drop table if exists statistics cascade;

    create table statistics (
       id int8 generated by default as identity,
        app varchar(50) not null,
        created_date timestamp not null,
        ip varchar(20) not null,
        uri varchar(50) not null,
        primary key (id)
    );
