
    drop table if exists statistics cascade;

    create table statistics (
       id int8 generated by default as identity,
        app varchar(50) not null,
        created_date timestamp not null,
        ip varchar(20) not null,
        uri varchar(50) not null,
        primary key (id)
    );
alter table if exists event_compilations drop constraint if exists FK1apfcv39op0iw4tmkrovgct53;
alter table if exists event_compilations drop constraint if exists FK6bxdd0vorbi0yivipvk5mai7p;
alter table if exists events drop constraint if exists FKo6mla8j1p5bokt4dxrlmgwc28;
alter table if exists events drop constraint if exists FKgsyp7tc40dhju9fq5i767kyun;
alter table if exists requests drop constraint if exists FKm7vtr0204t3xcymbx4sa9t1ot;
alter table if exists requests drop constraint if exists FKeoax2t4j9i61p9lmon3009tr4;
drop table if exists categories cascade;
drop table if exists compilations cascade;
drop table if exists event_compilations cascade;
drop table if exists events cascade;
drop table if exists requests cascade;
drop table if exists users cascade;

create table categories (
 id int8 generated by default as identity,
  name varchar(128) not null, primary key (id)
  );
create table compilations (
 id int8 generated by default as identity,
  pinned boolean not null,
   title varchar(64) not null,
    primary key (id)
    );
create table event_compilations (
 compilation_id int8 not null,
  event_id int8 not null);
create table events (
 id int8 generated by default as identity,
  annotation varchar(2000) not null,
   category_id int8,
    confirmed_requests int4,
     created_date timestamp not null,
      description varchar(7000) not null,
       event_date timestamp not null,
        initiator_id int8,
         lat float8 not null,
          lon float8 not null,
           paid boolean not null,
            participant_limit int4,
             published_on timestamp,
              request_moderation boolean,
               state varchar(32),
                title varchar(128),
                 views int4,
                  primary key (id)
                  );
create table requests (
 id int8 generated by default as identity,
  created_date timestamp not null,
   event_id int8,
    requester_id int8,
     status varchar(32),
      primary key (id)
      );
create table users (
 id int8 generated by default as identity,
  email varchar(256) not null,
   name varchar(256) not null,
    primary key (id));

alter table if exists categories add constraint UK_t8o6pivur7nn124jehx7cygw5 unique (name);
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists event_compilations add constraint FK1apfcv39op0iw4tmkrovgct53 foreign key (event_id) references events;
alter table if exists event_compilations add constraint FK6bxdd0vorbi0yivipvk5mai7p foreign key (compilation_id) references compilations;
alter table if exists events add constraint FKo6mla8j1p5bokt4dxrlmgwc28 foreign key (category_id) references categories;
alter table if exists events add constraint FKgsyp7tc40dhju9fq5i767kyun foreign key (initiator_id) references users on delete cascade;
alter table if exists requests add constraint FKm7vtr0204t3xcymbx4sa9t1ot foreign key (event_id) references events on delete cascade;
alter table if exists requests add constraint FKeoax2t4j9i61p9lmon3009tr4 foreign key (requester_id) references users on delete cascade;
