version: '3.8'
services:
  stats-server:
    restart: on-failure
    build: ./statistic-service/statistic-server
    container_name: stats-server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=explorer
      - SPRING_DATASOURCE_PASSWORD=iamroot

  stats-db:
    restart: on-failure
    image: postgres:15.3-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    volumes:
      - /stats-db-container
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=explorer
      - POSTGRES_PASSWORD=iamroot


